services:
  db:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    env_file:
      - ./archery/settings/.postgres.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    container_name: uwac-site-db
    hostname: uwac-site-db
    networks:
      - internal

  web-service:
    image: ghcr.io/davidjrichardson/uwac-site:2024-03-09
    depends_on:
      - db
    ports:
      - 8000:8000
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./archery/settings/.uwac-site.env
    environment:
      - DB_HOST=uwac-site-db
    container_name: uwac-site-web-service
    hostname: uwac-site-web-service
    networks:
      - internal
      - external

networks:
  internal:
  external: