# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('home', '0003_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='cover_image',
            field=models.ForeignKey(blank=True, help_text='This is the image displayed on the home page as the first thing a user will see', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='description',
            field=models.TextField(default='', max_length=400),
        ),
    ]
