# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_blogpage_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='cover_image_credit',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
