# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 21:54
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20170922_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryindexpage',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(default=''),
        ),
    ]
