# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_galleryindexpage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypage',
            name='gallery_cover',
            field=models.ForeignKey(help_text='This is the image displayed on the home page as the first thing a user will see', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
