# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-19 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20170926_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='cover_image_credit',
            field=models.CharField(blank=True, help_text='The author of the photograph for the image on the home page', max_length=100),
        ),
    ]
