# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-25 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_contentpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentpage',
            name='date',
        ),
    ]
