# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-04 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20180114_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='attribution',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
